#server:
#  port: 8081
#  servlet:
#    #访问项目名
#    context-path: /service
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.110.6:8848
#  application:
#    name: server-provider
#  kafka:
#    bootstrap-servers: 192.168.110.6:9092
#    producer:
#          key-serializer: org.apache.kafka.common.serialization.StringSerializer
#          value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#          group-id: test
#          enable-auto-commit: true
#          auto-commit-interval: 1000
#          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    listener:
#      log-container-config: false
#  datasource:
#    name: tmr
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/tmr
#    username: TMR
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#  #跳转页面需要配置
#  mvc:
#    static-path-pattern: /**
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: utf-8
#    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#    static-locations: classpath:/static/
#   #热部署
#  devtools:
#    restart:
#      enabled: true
#      #重启目录
#      additional-paths: src/main/java
#      exclude: WEB-INF/**
#  redis:
#    #redis 数据库索引
#    database: 0
#    #服务器地址
#    host: 192.168.110.6
#    #端口号
#    port: 6379
#    #密码
#    password:
#    jedis:
#      pool:
#       #连接池最大连接数
#        max-active: 200
#        #连接池最大阻塞等待时间 负数表示没有限制
#        max-wait: -1
#        #连接池最大空闲连接
#        max-idle: 10
#        #连接池最小空闲连接
#        min-idle: 0
#    #连接超时时间
#    timeout: 1000
#  data:
##    elasticsearch:
##      cluster-nodes: 127.0.0.1:9300
##      cluster-name: elasticsearch
##      repositories:
##        enabled: true
#
#
#
#      #classpath目录下的WEB-INF文件夹内容修改不重启
##扫描resources下的xmlmybatis-plus:
#mybatis-plus:
#  mapper-locations: classpath*:/mappers/*.xml
#  typeAliasesPackage: com.ning.service.entity
#logging:
#  path: D:/demo1/target/logout
##  pattern:
##    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
##    file: "%d{yyyy-MM-dd HH:mm:ss} === [%thread] === %-5level === %logger{50} ==== %msg%n"
#
#
#  #typeEnumsPackage: com.ning.service.entity.enums
#
